TIOT_HEADER_LIST += -I$(TIOT_DRIVER_PATH)/product_porting
TIOT_HEADER_LIST += -I$(TIOT_DRIVER_PATH)/product_porting/porting
include $(TIOT_DRIVER_PATH)/product_porting/porting/porting.mk
tiot-porting-objs := $(addprefix product_porting/porting/,$(tiot-porting-objs))