/* Copyright (c) @CompanyNameMagicTag 2022-2022. All rights reserved. */
#define CONFIG_DEV_TIOT_SLAVE 1
#define CONFIG_TIOT_SLAVE_DEV_NUM 1
#define CONFIG_TIOT_SLAVE_UART 1
#define CONFIG_TIOT_SLAVE_UART_BAUDRATE 115200
#define CONFIG_TIOT_SLAVE_UART_WITH_FLOWCTRL 1
#define CONFIG_FILE_BY_ARRAY 1
#define CONFIG_OSAL_DEFINED 1
#define CONFIG_LIBBOUNDSCHECK_IMPLEMENTED 1
#define CONFIG_BOARD_DYNAMIC_ALLOC 1
#define CONFIG_FIRMWARE_FILE_READ_BUF_LEN 1029
#define CONFIG_PM_MANAGE_LOWPOWER 1
#define CONFIG_XMIT_WITH_UART 1
#define CONFIG_UART_RX_MODE_BUFFED 1
#define CONFIG_XFER_PACKET_TIOT 1
#define CONFIG_XFER_DEFAULT_RX_BUFF 1
#define CONFIG_XFER_RX_BUFF_SIZE 512
